import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { DarkThemeToggle, ThemeModeScript } from "flowbite-react"
import "./globals.css"
import { Component as NavBar } from "./Components/NavBar"
import { Component as Footer } from "./Components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
