import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DarkThemeToggle, ThemeModeScript } from "flowbite-react";
import "./globals.css";
import { Component as NavBar } from "./Components/NavBar";
import { Component as Footer } from "./Components/Footer";

// Load the Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata for the document
export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Script to handle theme mode */}
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        {/* Navigation bar component */}
        <NavBar />
        {/* Main content */}
        {children}
        {/* Footer component */}
        <Footer />
      </body>
    </html>
  );
}
